# Generated by Django 3.0.6 on 2022-07-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cctv',
            table='cctv',
        ),
    ]
