# Generated by Django 3.0.6 on 2022-07-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220715_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctv',
            options={'managed': False},
        ),
    ]
