# Generated by Django 3.0.6 on 2022-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220715_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'db_table': 'lamp',
            },
        ),
        migrations.CreateModel(
            name='Loadpoint',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'db_table': 'loadpoint',
            },
        ),
        migrations.CreateModel(
            name='Securitycenter',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'securitycenter',
            },
        ),
    ]
